### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by mga121** [chanzer0/PGA-DFS-Tools#2] opened 2023-06-15 08:22 UTC
I keep on getting this same error message. Any clue what could be causing this? I think I have all my csv uploaded into the dk data folder correctly. Thanks a ton for providing this tool by the way! Very much appreciated

PS C:\Users\mga12\Desktop\PGA-DFS-Tools-main\src> python .\main.py dk opto 50 1
Traceback (most recent call last):
  File "C:\Users\mga12\Desktop\PGA-DFS-Tools-main\src\main.py", line 59, in <module>
    main(sys.argv)
  File "C:\Users\mga12\Desktop\PGA-DFS-Tools-main\src\main.py", line 21, in main
    opto = PGA_Optimizer(site, num_lineups, num_uniques)
           ^^^^^^^^^^^^^
NameError: name 'PGA_Optimizer' is not defined

**Comment by bjungwirth** [comment] 2023-06-15 15:36
Hey, this is because the optimizer isn't set up yet, only the simulator. 

python .\main.py dk sim [other arguments as in the readme here] is what will work for now.

**Comment by toonice17** [comment] 2023-06-15 22:11
Hey thanks for creating these tools! Im learning a lot about Python because of you two. :) I tried to create my own lineups as if the optimizer was working. So I could attempt to move on to the simulator step but i cant seem to get passed this error.

PS C:\Users\H\Desktop\PGA-DFS-Tools-main\src> python .\main.py dk sim cid file 100
Traceback (most recent call last):
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\main.py", line 59, in <module>
    main(sys.argv)
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\main.py", line 52, in main
    sim = PGA_GPP_Simulator(site, field_size, num_iterations, use_contest_data,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\pga_gpp_simulator.py", line 39, in __init__
    self.load_config()
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\pga_gpp_simulator.py", line 160, in load_config
    with open(os.path.join(os.path.dirname(__file__), '../config.json'), encoding='utf-8-sig') as json_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\H\\Desktop\\PGA-DFS-Tools-main\\src\\../config.json'

**Comment by bjungwirth** [comment] 2023-06-15 22:13
make sure config.json is in the base directory and not in .\src\

**Comment by toonice17** [comment] 2023-06-15 22:17
WOW, i did not expect such timely responses! Thank you!
I have confirmed this is correct. My config.json had an extra ".json" attached to it so i renamed it and got a similar but different error message.

PS C:\Users\H\Desktop\PGA-DFS-Tools-main\src> python .\main.py dk sim cid file 100
Traceback (most recent call last):
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\main.py", line 59, in <module>
    main(sys.argv)
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\main.py", line 52, in main
    sim = PGA_GPP_Simulator(site, field_size, num_iterations, use_contest_data,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\pga_gpp_simulator.py", line 39, in __init__
    self.load_config()
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\pga_gpp_simulator.py", line 161, in load_config
    self.config = json.load(json_file)
                  ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\H\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 18 (char 17)
PS C:\Users\H\Desktop\PGA-DFS-Tools-main\src>

**Comment by bjungwirth** [comment] 2023-06-15 22:19
looks like an error with the json formatting. can you post your config.json file? or use a json formatter https://jsonformatter.org/json-pretty-print and you should be able to find the issue

**Comment by toonice17** [comment] 2023-06-15 22:32
hmm, it wont let me upload json files and i when i try to put it into the formatter it says parse error on line 1
I found this sample in the README

"projection_path": "projections.csv", // This is where projections are loaded from -- the required columns are "Name" and "Fpts"
"ownership_path": "ownership.csv", // This is where ownership is loaded from -- the required columns are "Name" and "Own%"
"player_path": "player_ids.csv", // This is where player ids are loaded from -- this is the direct player ID export from DraftKings/Fanduel found on the contest or edit lineups page.
"boom_bust_path": "boom_bust.csv", // This is where boom/bust data is loaded from -- the required columns are "Name", "stddev", and "ceiling"
"contest_structure_path": "contest_structure.csv", // This is where GPP sim tournament strucure is loaded from -- as seen above, the required columns are "Place", "Payout", "Field Size", "Entry Fee"
"at_least": {
    "2": [
        ["Justin Thomas", "Jordan Spieth", "Tiger Woods"], // This will use at least 2 of these players
    ],
    "1": [
        ["Justin Thomas", "Jordan Spieth"], // This will use at least 1 of these players
    ],
},
"at_most": {
    "1": [
        ["Justin Thomas", "Jordan Spieth"], // Will use at most 1 of these players, useful if you're trying to avoid specific tee time stacks.
        ["Jon Rahm", "Brooks Koepka"],
    ],
    "2": [
        ["Justin Thomas", "Jordan Spieth", "Jon Rahm", "Brooks Koepka"], // Will use at most 2 of these players
    ],
},
"projection_minimum": 15, // No player projected under 15 fpts will be used
"randomness": 25, // 25% standard deviation randomness, or .25*stddev
"min_lineup_salary" : 48000, //minimum lineup salary to be used in the gpp simulation module
"max_pct_off_optimal" : 0.4 //maximum percent a lineup can be off the optimal in the gpp simulation module

**Comment by bjungwirth** [comment] 2023-06-15 22:41
paste the json in your config.json in a comment and then highlight and press ctrl+e (command+e if you're on mac) and it will convert it to code for me to look at

**Comment by toonice17** [comment] 2023-06-15 22:43
```
"projection_path": "projections.csv", // This is where projections are loaded from -- the required columns are "Name" and "Fpts"
"ownership_path": "ownership.csv", // This is where ownership is loaded from -- the required columns are "Name" and "Own%"
"player_path": "player_ids.csv", // This is where player ids are loaded from -- this is the direct player ID export from DraftKings/Fanduel found on the contest or edit lineups page.
"boom_bust_path": "boom_bust.csv", // This is where boom/bust data is loaded from -- the required columns are "Name", "stddev", and "ceiling"
"contest_structure_path": "contest_structure.csv", // This is where GPP sim tournament strucure is loaded from -- as seen above, the required columns are "Place", "Payout", "Field Size", "Entry Fee"
"at_least": {
    "2": [
        ["Justin Thomas", "Jordan Spieth", "Tiger Woods"], // This will use at least 2 of these players
    ],
    "1": [
        ["Justin Thomas", "Jordan Spieth"], // This will use at least 1 of these players
    ],
},
"at_most": {
    "1": [
        ["Justin Thomas", "Jordan Spieth"], // Will use at most 1 of these players, useful if you're trying to avoid specific tee time stacks.
        ["Jon Rahm", "Brooks Koepka"],
    ],
    "2": [
        ["Justin Thomas", "Jordan Spieth", "Jon Rahm", "Brooks Koepka"], // Will use at most 2 of these players
    ],
},
"projection_minimum": 15, // No player projected under 15 fpts will be used
"randomness": 25, // 25% standard deviation randomness, or .25*stddev
"min_lineup_salary" : 48000, //minimum lineup salary to be used in the gpp simulation module
"max_pct_off_optimal" : 0.4 //maximum percent a lineup can be off the optimal in the gpp simulation module
```

**Comment by bjungwirth** [comment] 2023-06-15 22:44
does it have curly brackets around the entire code block? like so:

```
{
  "projection_path": "projections.csv",
  "ownership_path": "ownership.csv",
  "player_path": "player_ids.csv",
  "boom_bust_path": "boom_bust.csv",
  "late_swap_path": "live_lineups.csv",
  "contest_structure_path": "contest_structure.csv",
  "at_most": {

  },
  "at_least": {
  },
  "matchup_limits": {
  },
  "matchup_at_least": {
  },
  "team_limits": {
  },
  "global_team_limit": 3,
  "projection_minimum": 9,
  "randomness": 100,
  "min_lineup_salary" : 49200,
  "max_pct_off_optimal" : 0.2
}
```

**Comment by toonice17** [comment] 2023-06-15 22:50
It does now! The error code has changed.

PS C:\Users\H\Desktop\PGA-DFS-Tools-main\src> python .\main.py dk sim cid file 100
Traceback (most recent call last):
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\main.py", line 59, in <module>
    main(sys.argv)
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\main.py", line 52, in main
    sim = PGA_GPP_Simulator(site, field_size, num_iterations, use_contest_data,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\pga_gpp_simulator.py", line 39, in __init__
    self.load_config()
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\pga_gpp_simulator.py", line 161, in load_config
    self.config = json.load(json_file)
                  ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\H\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 39 (char 40)

**Comment by chanzer0** [comment] 2023-06-15 22:53
I think another thing with the config - you don't want any comments in there. So on lines where you have `// a comment is here`, delete those two forward slashes and anything to the right of it

**Comment by bjungwirth** [comment] 2023-06-15 22:53
copy and paste the config with the curly brackets i just posted and make sure it works. then you can go back in and tweak the values to your liking. 

here's a good tutorial about how json formatting works as well: https://www.guru99.com/json-tutorial-example.html

**Comment by toonice17** [comment] 2023-06-15 22:56
Thanks so much for your time, I really appreciate the help! I copied what you posted and tried to run the sim again. I look forward to reading the tutorial you posted. This is the error i got.

PS C:\Users\H\Desktop\PGA-DFS-Tools-main\src> python .\main.py dk sim cid file 100
Traceback (most recent call last):
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\main.py", line 59, in <module>
    main(sys.argv)
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\main.py", line 52, in main
    sim = PGA_GPP_Simulator(site, field_size, num_iterations, use_contest_data,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\pga_gpp_simulator.py", line 65, in __init__
    self.load_contest_data(contest_path)
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\pga_gpp_simulator.py", line 137, in load_contest_data
    self.entry_fee = float(row['Entry Fee'])
                           ~~~^^^^^^^^^^^^^
KeyError: 'Entry Fee'

**Comment by bjungwirth** [comment] 2023-06-15 22:58
No problem! Happy you're checking it out. Now make sure that your 'contest_structure.csv' file in /dk_data/ is structured and formatted exactly as pictured in the readme. That error is saying that it can't find the "Entry Fee" column (key) in the contest structure file.

Also -- when you create your contest structure file make sure that excel isn't converting things like '7-8' to 'July 8".

**Comment by toonice17** [comment] 2023-06-15 23:07
The excel date thing is SUPER ANNOYING, i used google sheets for that because i couldnt figure out how to format it. On closer examination i realize that when i open the CSV it changes the google numbers back to dates again

**Comment by chanzer0** [comment] 2023-06-15 23:08
Yeah I tend to stick to Google sheets for ease of formatting

**Comment by toonice17** [comment] 2023-06-15 23:12
Okay I feel like were close! this is the new error

PS C:\Users\H\Desktop\PGA-DFS-Tools-main\src> python .\main.py dk sim cid file 100
Contest payout structure loaded.
loading lineups
Traceback (most recent call last):
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\main.py", line 59, in <module>
    main(sys.argv)
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\main.py", line 52, in main
    sim = PGA_GPP_Simulator(site, field_size, num_iterations, use_contest_data,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\pga_gpp_simulator.py", line 74, in __init__
    self.load_lineups_from_file()
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\pga_gpp_simulator.py", line 224, in load_lineups_from_file
    lineup = [row[0].split('(')[0][:-1].replace('-', '#').lower(), row[1].split('(')[0][:-1].replace('-', '#').lower(),
              ^^^^^^^^^^^^
AttributeError: 'float' object has no attribute 'split'

**Comment by bjungwirth** [comment] 2023-06-15 23:12
> I keep on getting this same error message. Any clue what could be causing this? I think I have all my csv uploaded into the dk data folder correctly. Thanks a ton for providing this tool by the way! Very much appreciated
> 
> PS C:\Users\mga12\Desktop\PGA-DFS-Tools-main\src> python .\main.py dk opto 50 1 Traceback (most recent call last): File "C:\Users\mga12\Desktop\PGA-DFS-Tools-main\src\main.py", line 59, in main(sys.argv) File "C:\Users\mga12\Desktop\PGA-DFS-Tools-main\src\main.py", line 21, in main opto = PGA_Optimizer(site, num_lineups, num_uniques) ^^^^^^^^^^^^^ NameError: name 'PGA_Optimizer' is not defined

we just merged the optimizer if you want to give it a try

**Comment by bjungwirth** [comment] 2023-06-15 23:14
> 

what does your "tournament_lineups.csv" file look like? there's a screenshotted example of how it should look in the readme:

![image](https://github.com/chanzer0/PGA-DFS-Tools/assets/23266041/6d581536-8aa8-4606-ad76-44ade4c5ea71)

**Comment by toonice17** [comment] 2023-06-15 23:14
![image](https://github.com/chanzer0/PGA-DFS-Tools/assets/78042345/8aba797f-0ae8-431c-9a58-a8c0105307f5)

**Comment by bjungwirth** [comment] 2023-06-15 23:16
> ![image](https://user-images.githubusercontent.com/78042345/246269691-8aba797f-0ae8-431c-9a58-a8c0105307f5.png)

if you move the six "G" columns to the left of salary/fpts proj it will work. since every column on exported lineups have the same name ("G") we have to tell python which columns to use by position on the sheet. we'll find a better way to do it later.

`row[0].split('(')[0][:-1].replace('-', '#')` means "take the value of the first column in each row, split it by parentheses to sort out ID and Name and then replace hyphens with #"

**Comment by toonice17** [comment] 2023-06-15 23:21
LOL is it a total coincidence that its coming up with Matt Fitzpatrick, i know there is the name change thing which i ran right after and tried again but got the same error.

PS C:\Users\H\Desktop\PGA-DFS-Tools-main\src> python .\name_change.py
FD Projections failed to rename
FD Ownership failed to rename
FD Boom/Bust failed to rename
PS C:\Users\H\Desktop\PGA-DFS-Tools-main\src> python .\main.py dk sim cid file 100
Contest payout structure loaded.
loading lineups
supplied lineups >= contest field size. only retrieving the first 475 lineups
Running 100 simulations
Traceback (most recent call last):
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\main.py", line 59, in <module>
    main(sys.argv)
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\main.py", line 55, in main
    sim.run_tournament_simulation()
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\pga_gpp_simulator.py", line 348, in run_tournament_simulation
    fpts_sim = sum([temp_fpts_dict[player]
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\Desktop\PGA-DFS-Tools-main\src\pga_gpp_simulator.py", line 348, in <listcomp>
    fpts_sim = sum([temp_fpts_dict[player]
                    ~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'matt fitzpatrick'

**Comment by bjungwirth** [comment] 2023-06-15 23:28
It's definitely not a coincidence. In any of your input files are player names lowercased? name_change looks for "Matt Fitzpatrick" and not "matt fitzpatrick" -- that's a bug we'll have to fix

**Comment by toonice17** [comment] 2023-06-15 23:41
It was indeed Fitzpatrick's doing. Idk how one of the sheets had Matthew I literally copied them all from the same salaries sheet. Congratulations gentlemen.

PS C:\Users\H\Desktop\PGA-DFS-Tools-main\src> python .\main.py dk sim cid file 100
Contest payout structure loaded.
loading lineups
supplied lineups >= contest field size. only retrieving the first 475 lineups
Running 100 simulations
100 tournament simulations finished in 0.00954127311706543seconds. Outputting.

**Comment by bjungwirth** [comment] 2023-06-15 23:42
Awesome. I'm gonna mark this closed since we have the optimizer up as well.

**Closed as completed** 2023-06-16 14:58 UTC
